### ISSUE TITLE
OKD Working Group Meeting Time 

### ISSUE THREAD

**Issue by dmueller2001** [openshift/community#49]
At the last OKD WG mtg, the OKD Working Group Meeting time was set to 17:00 UTC on Tuesdays on a Bi-weekly cadence on Tuesdays.

However, the group wanted to open a discussion on the optimal time for the call. 

If you have feedback on the 17:00 UTC time that we've settled on, please add a comment. 

If you are okay with the 17:00 UTC time, give the issue a thumbs up in the reaction option.

**Comment by slaterx** [comment]
Hi, I would like to bring forward the meeting time in one hour, to 18:00 UTC. The reason being because I'm based in New Zealand and it is easier to join the call 6am my time instead of 5am. 

Thanks,
Gleidson
