### ISSUE TITLE
Proposed Topic: MetalKube update

### ISSUE THREAD

**Issue by dmueller2001** [openshift/community#52]
Invite the MetalKube team to upcoming mtg Oct 15 - Clayton/Diane - ask Russell Bryant

**Comment by hardys** [comment]
Hi @dmueller2001 I've only now seen this, seems we missed the previous meeting slot but I'd be happy to help in a subsequent meeting if you can add me to the invite.  I've been working with @russellb leading the Openshift baremetal IPI integration of metal3.

Perhaps you or @smarterclayton can provide a bit more context as to what the group would be looking at in terms of an update, and areas of potential interest/overlap?

**Comment by hardys** [comment]
Found the invite at https://github.com/openshift/community/projects/1 - feel free to assign this agenda item to me and I'll prepare a couple of slides to talk around tomorrow.
