### ISSUE TITLE
Proposed OKD-WG Mtg Topic: Evolution of cluster self-management with etcd

### ISSUE THREAD

**Issue by dmueller2001** [openshift/community#53]
requested for Oct 15th 17:00 UTC meeting
suggested speaker to request: Sam Batschelet @hexfusion

Sam, if you are available for the next OKD-WG, we'd like to have you come and present on this topic for 10-15 max at Clayton's suggestion. Could you confirm if you are available?

**Comment by hexfusion** [comment]
@dmueller2001 @smarterclayton, I can make this work please let me know if there is anything else I need to know.
