### ISSUE TITLE
Proposed Topic: Code-Ready Containers and OKD4

### ISSUE THREAD

**Issue by dmueller2001** [openshift/community#54]
OKD-WG Mtg: Oct 29h 17:00 UTC
Suggested Speaker: @cgruver Charro Gruver

If you look at these two repos:
Code Ready Containers:  https://github.com/code-ready/crc
Single Node Cluster:        https://github.com/code-ready/snc
You can get a feel for what we'll need to do to make it work with OKD4.  It really should not be too big a deal.  I've been playing with building crc from source and using snc to build a bundle that crc can consume.  I use an openshift-installer built from the 4.1 branch with Libvirt support enabled.
There's still some rough edges, and it's currently dependent on pulling RHCOS from the official redhat registry and OCP images from either quay.io or the redhat registry.
But, there's definitely a path for us to modify it to pull FCOS qcows images for the OS and to take an OKD image from a local or public registry.

**Comment by cgruver** [comment]
I've had a work related meeting dropped on my calendar for Tuesday that I need to give priority to.  I won't be able to attend this time.

**Comment by cgruver** [comment]
I spent some time on this over the weekend.  The results are summarized in an issue opened in the OKD repo.

https://github.com/openshift/okd/issues/88

**Comment by cfergeau** [comment]
Initial okd work has  been merged in snc https://github.com/code-ready/snc/commit/347387881544c7fda421ec38550884c59b431e5c though this could be refined further.
A PR for crc has been submitted https://github.com/code-ready/crc/pull/1511
There also has been releases of crc+okd at https://www.okd.io/crc.html but I have no idea what this is coming from.

**Comment by cgruver** [comment]
@cfergeau The current CRC for OKD releases are being built from the crc fork in my GitHub repo.  That's where the PR is from too.  The PR needs a rebase, and we need to work out the best way to include OKD compatibility.  But, we'll work that out in the crc repo.

The bundle for the releases is built from code-ready/snc, now that we have the initial PR merged.

@dmueller2001  We can probably close this issue now that we've advanced this topic through the working group.  The rest of the work for CRC + OKD is being tracked in the relevant code-ready repos.

Cheers

**Comment by guillaumerose** [comment]
crc now uses the `oc` client located in the bundle. Current crc can be used for okd without any modifications. 
We can still improve the workflow for the pull secret.

**Comment by cgruver** [comment]
Yes.  I plan to dig into the crc code, hopefully this weekend, and add logic to use a default pull secret for OKD.

I'm also going to make the version reflect OKD so that folks can easily see what they are running.
