### ISSUE TITLE
Packit for OKD<->Fedora integration

### ISSUE THREAD

**Issue by Conan-Kudo** [openshift/community#59]
In the previous OKD WG meetings, we've discussed [Packit](https://packit.dev) and how we'd like to use it to make integrating OKD code into Fedora a lot smoother.

There seems to be some confusion about Packit's current state of affairs as well as its goals.

@TomasTomecek, could you comment on this (and perhaps come to an OKD WG meeting to discuss this?)

**Comment by LorbusChris** [comment]
/cc @dustymabe

(see also: https://github.com/openshift/community/projects/1#card-28314476 )

**Comment by LorbusChris** [comment]
Upstream issue: https://github.com/packit-service/packit-service/issues/47

**Comment by TomasTomecek** [comment]
Howdy! Thanks for your interest in the packit service!

The current status of packit in terms of Fedora infra integration is that packit is able to push changes to dist-git or open a PR against dist-git: [check propose_downstream job](https://packit.dev/docs/configuration/#supported-jobs)

The build part is in the works: we have scoped a task for it yesterday to be honest and we'll work on it in the coming sprints, that's all I can promise right now.

**Comment by LorbusChris** [comment]
I've been meaning to add a user story for this in the respective repo in `packit-service` when I find time for it.

**Comment by TomasTomecek** [comment]
It's been ~8 months since we spoke and gotta say a ton of changed on our side: wanna refresh this effort?

**Comment by LorbusChris** [comment]
I think we currently don't have a use case for Packit in OKD, since we're not using RPMs for packaging the oc and machine-config-daemon binaries there anymore.

There are some other projects in the Fedora CoreOS and IoT realm though where this will come in handy.

I'll close this issue here for now.
