### ISSUE TITLE
[Proposed Agenda Item] Remove references to 3.x from the website and various repo pages

### ISSUE THREAD

**Issue by JaimeMagiera** [openshift/community#66]
Given that users are now explicitly being told to move from 3.x, does the Working Group think we should remove references to it from the OKD website and the various repo pages? The links could be replaced with a note along the lines of "OKD v.3 is no longer receiving updates. Please consider moving to OKD 4."

**Comment by reenberg** [comment]
Not sure when it was added, but I guess this has already been done.  Though the text could be updated to be in past tense now, and perhaps even include links to [migration notes](https://docs.okd.io/latest/migrating_from_ocp_3_to_4/about-migrating-from-3-to-4.html).  
But this issue could be closed, as it is worded right now? unless something else was agreed on the meeting.

![image](https://user-images.githubusercontent.com/34238/129263464-b3269255-8a0f-4e6e-8de9-255f1e140d73.png)
